### PR TITLE
Added a dark themed toggle

### PR DESCRIPTION
**Pull request by Ayush-Khandelwal-007**
#6 Implement Dark mode in the application
**Implemented dark mode in the app** that could be done with the help of a _toggle switch_ placed at the navigation bar, _trying not to disturb the original layout_ at max.Also the **dark mode persist even after refreshing** the page

Here are some sample screenshots of new version of your app.

Screenshot 2020-10-11 at 4 06 38 AM
Screenshot 2020-10-11 at 4 06 43 AM
Screenshot 2020-10-11 at 4 08 05 AM
Screenshot 2020-10-11 at 4 07 55 AM

### CODE REVIEW

**Review by amanjagdev — CHANGES_REQUESTED** [review]
@Ayush-Khandelwal-007  Everything looks good, There is only one change that's required, i.e. Dark mode doesn't get reflected on the text inputs.
Please do the above-mentioned changes too.

**Comment by Ayush-Khandelwal-007** [comment]
Done the changes.

**Comment by Ayush-Khandelwal-007** [comment]
Screenshot 2020-10-13 at 2 21 14 PM
Screenshot 2020-10-13 at 2 21 18 PM
Screenshot 2020-10-13 at 2 21 21 PM
Screenshot 2020-10-13 at 2 21 24 PM

**Comment by amanjagdev** [comment]
@Ayush-Khandelwal-007  This looks good :)
Great work .

**Review by amanjagdev — APPROVED** [review]

**Pull request merged**
